import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function getLanguageName(languageCode: string): string {
  const languageNames: Record<string, string> = {
    'en-US': 'English (US)',
    'en-GB': 'English (UK)',
    'es-ES': 'Spanish (Spain)',
    'es-MX': 'Spanish (Mexico)',
    'fr-FR': 'French (France)',
    'de-DE': 'German (Germany)',
    'it-IT': 'Italian (Italy)',
    'pt-BR': 'Portuguese (Brazil)',
    'pt-PT': 'Portuguese (Portugal)',
    'ru-RU': 'Russian (Russia)',
    'ja-JP': 'Japanese (Japan)',
    'ko-KR': 'Korean (South Korea)',
    'zh-CN': 'Chinese (Simplified)',
    'zh-TW': 'Chinese (Traditional)',
    'ar-SA': 'Arabic (Saudi Arabia)',
    'hi-IN': 'Hindi (India)',
    'th-TH': 'Thai (Thailand)',
    'vi-VN': 'Vietnamese (Vietnam)',
    'nl-NL': 'Dutch (Netherlands)',
    'sv-SE': 'Swedish (Sweden)',
    'no-NO': 'Norwegian (Norway)',
    'da-DK': 'Danish (Denmark)',
    'fi-FI': 'Finnish (Finland)',
    'pl-PL': 'Polish (Poland)',
    'tr-TR': 'Turkish (Turkey)',
    'cs-CZ': 'Czech (Czech Republic)',
    'hu-HU': 'Hungarian (Hungary)',
    'ro-RO': 'Romanian (Romania)',
    'bg-BG': 'Bulgarian (Bulgaria)',
    'hr-HR': 'Croatian (Croatia)',
    'sk-SK': 'Slovak (Slovakia)',
    'sl-SI': 'Slovenian (Slovenia)',
    'et-EE': 'Estonian (Estonia)',
    'lv-LV': 'Latvian (Latvia)',
    'lt-LT': 'Lithuanian (Lithuania)',
    'el-GR': 'Greek (Greece)',
    'he-IL': 'Hebrew (Israel)',
    'uk-UA': 'Ukrainian (Ukraine)',
    'be-BY': 'Belarusian (Belarus)',
    'ka-GE': 'Georgian (Georgia)',
    'hy-AM': 'Armenian (Armenia)',
    'az-AZ': 'Azerbaijani (Azerbaijan)',
    'kk-KZ': 'Kazakh (Kazakhstan)',
    'ky-KG': 'Kyrgyz (Kyrgyzstan)',
    'uz-UZ': 'Uzbek (Uzbekistan)',
    'mn-MN': 'Mongolian (Mongolia)',
    'ne-NP': 'Nepali (Nepal)',
    'si-LK': 'Sinhala (Sri Lanka)',
    'ta-IN': 'Tamil (India)',
    'te-IN': 'Telugu (India)',
    'kn-IN': 'Kannada (India)',
    'ml-IN': 'Malayalam (India)',
    'gu-IN': 'Gujarati (India)',
    'pa-IN': 'Punjabi (India)',
    'bn-IN': 'Bengali (India)',
    'or-IN': 'Odia (India)',
    'as-IN': 'Assamese (India)',
    'mr-IN': 'Marathi (India)',
    'ur-PK': 'Urdu (Pakistan)',
    'fa-IR': 'Persian (Iran)',
    'ps-AF': 'Pashto (Afghanistan)',
    'sd-PK': 'Sindhi (Pakistan)',
    'bo-CN': 'Tibetan (China)',
    'my-MM': 'Burmese (Myanmar)',
    'km-KH': 'Khmer (Cambodia)',
    'lo-LA': 'Lao (Laos)',
    'am-ET': 'Amharic (Ethiopia)',
    'sw-KE': 'Swahili (Kenya)',
    'zu-ZA': 'Zulu (South Africa)',
    'af-ZA': 'Afrikaans (South Africa)',
    'sq-AL': 'Albanian (Albania)',
    'eu-ES': 'Basque (Spain)',
    'ca-ES': 'Catalan (Spain)',
    'gl-ES': 'Galician (Spain)',
    'cy-GB': 'Welsh (UK)',
    'ga-IE': 'Irish (Ireland)',
    'is-IS': 'Icelandic (Iceland)',
    'mt-MT': 'Maltese (Malta)',
    'mk-MK': 'Macedonian (North Macedonia)',
    'sr-RS': 'Serbian (Serbia)',
    'bs-BA': 'Bosnian (Bosnia and Herzegovina)',
    'me-ME': 'Montenegrin (Montenegro)',
    'sq-XK': 'Albanian (Kosovo)'
  }
  
  return languageNames[languageCode] || languageCode
}